name: Build and test application
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
env:
  NEXT_PUBLIC_API_URL: http://localhost
jobs:
  # Build job
  test:
    runs-on: ubuntu-latest
    services:
      laravel:
        image: daamian3/fleet-tracker:latest
        ports:
          - '9000:9000'
        env:
          APP_URL: ${{ env.NEXT_PUBLIC_API_URL }}
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_DATABASE: testing
          DB_PASSWORD: ''
          MAIL_MAILER: log
          BROADCAST_DRIVER: log
          QUEUE_CONNECTION: sync
          TELESCOPE_ENABLED: false
      mariadb:
        image: mariadb:10
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    timeout-minutes: 5
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup nginx
        run: docker run --name nginx -d -p 80:80 -v $(pwd)/.github/workflows/nginx.conf:/etc/nginx/nginx.conf nginx:stable-alpine
      - name: Check api
        run: |
          docker ps
          sleep 3
          curl -f ${{ env.NEXT_PUBLIC_API_URL }} || exit 1
#      - uses: pnpm/action-setup@v2
#        with:
#          version: 8
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}
#          cache: 'pnpm'
#      - name: Restore cache
#        uses: actions/cache@v3
#        with:
#          path: |
#            .next/cache
#            .cache/Cypress
#          # Generate a new cache whenever packages or source files change.
#          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
#          # If source files changed but packages didn't, rebuild from a prior cache.
#          restore-keys: |
#            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-
#      - name: Install dependencies
#        run: pnpm install
#      - name: Unit and integration tests
#        run: pnpm test:ci
#      - name: Cypress run
#        uses: cypress-io/github-action@v5
#        with:
#          build: pnpm build
#          start: pnpm start
#          browser: chrome
