name: Build and test application
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
env:
  NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
jobs:
  # Build job
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            .cache/Cypress
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-
      - name: Install dependencies
        run: pnpm install
      - name: Unit and integration tests
        run: pnpm test:ci
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: pnpm build
          start: pnpm start
          browser: chrome
